// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: feedback_type.proto

package protopb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeedbackType int32

const (
	FeedbackType_FEEDBACK_UNSPECIFIED FeedbackType = 0
	FeedbackType_PRETENSION           FeedbackType = 1
	FeedbackType_WISH                 FeedbackType = 2
	FeedbackType_GRATITUDE            FeedbackType = 3
)

// Enum value maps for FeedbackType.
var (
	FeedbackType_name = map[int32]string{
		0: "FEEDBACK_UNSPECIFIED",
		1: "PRETENSION",
		2: "WISH",
		3: "GRATITUDE",
	}
	FeedbackType_value = map[string]int32{
		"FEEDBACK_UNSPECIFIED": 0,
		"PRETENSION":           1,
		"WISH":                 2,
		"GRATITUDE":            3,
	}
)

func (x FeedbackType) Enum() *FeedbackType {
	p := new(FeedbackType)
	*p = x
	return p
}

func (x FeedbackType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FeedbackType) Descriptor() protoreflect.EnumDescriptor {
	return file_feedback_type_proto_enumTypes[0].Descriptor()
}

func (FeedbackType) Type() protoreflect.EnumType {
	return &file_feedback_type_proto_enumTypes[0]
}

func (x FeedbackType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FeedbackType.Descriptor instead.
func (FeedbackType) EnumDescriptor() ([]byte, []int) {
	return file_feedback_type_proto_rawDescGZIP(), []int{0}
}

var File_feedback_type_proto protoreflect.FileDescriptor

const file_feedback_type_proto_rawDesc = "" +
	"\n" +
	"\x13feedback_type.proto\x12\x05enums*Q\n" +
	"\fFeedbackType\x12\x18\n" +
	"\x14FEEDBACK_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"PRETENSION\x10\x01\x12\b\n" +
	"\x04WISH\x10\x02\x12\r\n" +
	"\tGRATITUDE\x10\x03B3Z1github.com/podpivasniki1488/assyl-backend/protopbb\x06proto3"

var (
	file_feedback_type_proto_rawDescOnce sync.Once
	file_feedback_type_proto_rawDescData []byte
)

func file_feedback_type_proto_rawDescGZIP() []byte {
	file_feedback_type_proto_rawDescOnce.Do(func() {
		file_feedback_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feedback_type_proto_rawDesc), len(file_feedback_type_proto_rawDesc)))
	})
	return file_feedback_type_proto_rawDescData
}

var file_feedback_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_feedback_type_proto_goTypes = []any{
	(FeedbackType)(0), // 0: enums.FeedbackType
}
var file_feedback_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_feedback_type_proto_init() }
func file_feedback_type_proto_init() {
	if File_feedback_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feedback_type_proto_rawDesc), len(file_feedback_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_feedback_type_proto_goTypes,
		DependencyIndexes: file_feedback_type_proto_depIdxs,
		EnumInfos:         file_feedback_type_proto_enumTypes,
	}.Build()
	File_feedback_type_proto = out.File
	file_feedback_type_proto_goTypes = nil
	file_feedback_type_proto_depIdxs = nil
}
