// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: order_types.proto

package protopb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_CLEANING               OrderType = 1
	OrderType_INTERNET               OrderType = 2
	OrderType_GARBAGE_REMOVAL        OrderType = 3
	OrderType_PLUMBER                OrderType = 4
	OrderType_ELECTRICITY            OrderType = 5
	OrderType_OTHER                  OrderType = 6
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "CLEANING",
		2: "INTERNET",
		3: "GARBAGE_REMOVAL",
		4: "PLUMBER",
		5: "ELECTRICITY",
		6: "OTHER",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"CLEANING":               1,
		"INTERNET":               2,
		"GARBAGE_REMOVAL":        3,
		"PLUMBER":                4,
		"ELECTRICITY":            5,
		"OTHER":                  6,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_types_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_order_types_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_order_types_proto_rawDescGZIP(), []int{0}
}

var File_order_types_proto protoreflect.FileDescriptor

const file_order_types_proto_rawDesc = "" +
	"\n" +
	"\x11order_types.proto\x12\x05enums*\x81\x01\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bCLEANING\x10\x01\x12\f\n" +
	"\bINTERNET\x10\x02\x12\x13\n" +
	"\x0fGARBAGE_REMOVAL\x10\x03\x12\v\n" +
	"\aPLUMBER\x10\x04\x12\x0f\n" +
	"\vELECTRICITY\x10\x05\x12\t\n" +
	"\x05OTHER\x10\x06B3Z1github.com/podpivasniki1488/assyl-backend/protopbb\x06proto3"

var (
	file_order_types_proto_rawDescOnce sync.Once
	file_order_types_proto_rawDescData []byte
)

func file_order_types_proto_rawDescGZIP() []byte {
	file_order_types_proto_rawDescOnce.Do(func() {
		file_order_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_types_proto_rawDesc), len(file_order_types_proto_rawDesc)))
	})
	return file_order_types_proto_rawDescData
}

var file_order_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_types_proto_goTypes = []any{
	(OrderType)(0), // 0: enums.OrderType
}
var file_order_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_order_types_proto_init() }
func file_order_types_proto_init() {
	if File_order_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_types_proto_rawDesc), len(file_order_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_types_proto_goTypes,
		DependencyIndexes: file_order_types_proto_depIdxs,
		EnumInfos:         file_order_types_proto_enumTypes,
	}.Build()
	File_order_types_proto = out.File
	file_order_types_proto_goTypes = nil
	file_order_types_proto_depIdxs = nil
}
