// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/apartment": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Возвращает квартиру по этажу и номеру двери.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apartment"
                ],
                "summary": "Get apartment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Этаж",
                        "name": "floor",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Номер двери",
                        "name": "door_number",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Квартира найдена",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-model_Apartment"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "404": {
                        "description": "Квартира не найдена",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/apartment/bind": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Привязывает квартиру к текущему авторизованному пользователю.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apartment"
                ],
                "summary": "Bind apartment to user",
                "parameters": [
                    {
                        "description": "Bind apartment request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.bindApartmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Квартира успешно привязана к пользователю",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос (невалидный JSON или тело)",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Неавторизован (отсутствует или неверный JWT)",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "404": {
                        "description": "Квартира не найдена",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "409": {
                        "description": "Квартира уже привязана к пользователю",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/apartment/create": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Создаёт новую квартиру.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apartment"
                ],
                "summary": "Create apartment",
                "parameters": [
                    {
                        "description": "Create apartment request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.createApartmentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Квартира успешно создана",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "409": {
                        "description": "Квартира уже существует (конфликт)",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/auth/confirm": {
            "post": {
                "description": "Подтверждает пользователя по OTP-коду.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Confirm registration",
                "parameters": [
                    {
                        "description": "Confirm request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.confirmRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Подтверждение прошло успешно"
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Заходит по логину отдавая jwt токен.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login into account",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успех",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Регистрирует нового пользователя и отправляет OTP на указанный username (телефон/почта).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register new user",
                "parameters": [
                    {
                        "description": "Register request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная регистрация",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/reservation": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список бронирований текущего пользователя за период (from-to).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservation"
                ],
                "summary": "Get user reservations",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2025-12-29T10:00:00Z",
                        "description": "Start datetime (RFC3339)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2025-12-29T12:00:00Z",
                        "description": "End datetime (RFC3339)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успех",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-array_model_CinemaReservation"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "403": {
                        "description": "Нет доступа",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт бронирование на указанный период для текущего пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservation"
                ],
                "summary": "Create reservation",
                "parameters": [
                    {
                        "description": "Create reservation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.createReservationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успех",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "403": {
                        "description": "Нет доступа",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/reservation/approve": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Одобряет бронирование по reservation_id. Доступно только администратору.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservation"
                ],
                "summary": "Approve reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "reservation_id",
                        "name": "reservation_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Одобрено"
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "403": {
                        "description": "Только админ может одобрять",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.DefaultResponse-array_model_CinemaReservation": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CinemaReservation"
                    }
                },
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http.DefaultResponse-error": {
            "type": "object",
            "properties": {
                "data": {},
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http.DefaultResponse-model_Apartment": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.Apartment"
                },
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http.DefaultResponse-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http.bindApartmentRequest": {
            "type": "object",
            "required": [
                "apartment_id"
            ],
            "properties": {
                "apartment_id": {
                    "type": "string"
                }
            }
        },
        "http.confirmRequest": {
            "type": "object",
            "required": [
                "otp_code",
                "username"
            ],
            "properties": {
                "otp_code": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "http.createApartmentRequest": {
            "type": "object",
            "required": [
                "door_num",
                "floor"
            ],
            "properties": {
                "door_num": {
                    "type": "integer"
                },
                "floor": {
                    "type": "integer"
                }
            }
        },
        "http.createReservationRequest": {
            "type": "object",
            "required": [
                "from",
                "people_num",
                "to"
            ],
            "properties": {
                "from": {
                    "type": "string"
                },
                "people_num": {
                    "type": "integer"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "http.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "http.registerRequest": {
            "type": "object",
            "required": [
                "first_name",
                "last_name",
                "password",
                "username"
            ],
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "model.Apartment": {
            "type": "object",
            "properties": {
                "door_number": {
                    "type": "integer"
                },
                "floor": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                }
            }
        },
        "model.CinemaReservation": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_approved": {
                    "type": "boolean"
                },
                "people_num": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "assyl-c9b2197f0ace.herokuapp.com",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Assyl Backend API",
	Description:      "API для работы с приложением для ЖК.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
