// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/apartment": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Возвращает квартиру по этажу и номеру двери.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apartment"
                ],
                "summary": "Get apartment",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Этаж",
                        "name": "floor",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Номер двери",
                        "name": "door_number",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Квартира найдена",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-model_Apartment"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "404": {
                        "description": "Квартира не найдена",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/apartment/bind": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Привязывает квартиру к текущему авторизованному пользователю.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apartment"
                ],
                "summary": "Bind apartment to user",
                "parameters": [
                    {
                        "description": "Bind apartment request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.bindApartmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Квартира успешно привязана к пользователю",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос (невалидный JSON или тело)",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Неавторизован (отсутствует или неверный JWT)",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "404": {
                        "description": "Квартира не найдена",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "409": {
                        "description": "Квартира уже привязана к пользователю",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/apartment/create": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Создаёт новую квартиру.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apartment"
                ],
                "summary": "Create apartment",
                "parameters": [
                    {
                        "description": "Create apartment request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.createApartmentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Квартира успешно создана",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "409": {
                        "description": "Квартира уже существует (конфликт)",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/auth/confirm": {
            "post": {
                "description": "Подтверждает пользователя по OTP-коду.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Confirm registration",
                "parameters": [
                    {
                        "description": "Confirm request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.confirmRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Подтверждение прошло успешно"
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Заходит по логину отдавая jwt токен.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login into account",
                "parameters": [
                    {
                        "description": "Login request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успех",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-http_loginResponse"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Регистрирует нового пользователя и отправляет OTP на указанный username (телефон/почта).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register new user",
                "parameters": [
                    {
                        "description": "Register request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная регистрация",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/channel": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns channel messages within the time period.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "Get channel messages",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2025-12-01T00:00:00Z",
                        "description": "From datetime (RFC3339)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2025-12-02T00:00:00Z",
                        "description": "To datetime (RFC3339)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-array_model_ChannelMessage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sends a message to the channel. Only ADMIN or GOD can send.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "Send channel message",
                "parameters": [
                    {
                        "description": "Message payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.sendChannelMessage"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/feedback": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns feedbacks list (only ADMIN or GOD)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feedback"
                ],
                "summary": "Get feedbacks",
                "parameters": [
                    {
                        "type": "string",
                        "format": "date-time",
                        "example": "2026-01-01T00:00:00Z",
                        "description": "Created from (RFC3339)",
                        "name": "created_at_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "date-time",
                        "example": "2026-01-02T00:00:00Z",
                        "description": "Created to (RFC3339)",
                        "name": "created_at_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Text filter",
                        "name": "text",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Feedback type",
                        "name": "feedback_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates feedback message from authorized user",
                "tags": [
                    "feedback"
                ],
                "summary": "Create feedback",
                "parameters": [
                    {
                        "description": "Feedback payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.createFeedbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/order": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список заказов по фильтрам. Требуется JWT. Роль берётся из токена/контекста.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Get orders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID (uuid)",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User ID (uuid)",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Order type (string, must match protopb.OrderType enum name)",
                        "name": "order_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by text",
                        "name": "text",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успех",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-array_model_Order"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Не авторизован / некорректный user_id в токене",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт заявку/заказ от имени авторизованного пользователя. OrderType должен существовать в enum protopb.OrderType.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order"
                ],
                "summary": "Create order",
                "parameters": [
                    {
                        "description": "Create order request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.createOrderRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успех (No Content)",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Не авторизован / некорректный user_id в токене",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "422": {
                        "description": "Невалидный order_type",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/reservation": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список бронирований текущего пользователя за период (from-to).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservation"
                ],
                "summary": "Get user reservations",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2025-12-29T10:00:00Z",
                        "description": "Start datetime (RFC3339)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2025-12-29T12:00:00Z",
                        "description": "End datetime (RFC3339)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успех",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-array_model_CinemaReservation"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "403": {
                        "description": "Нет доступа",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создаёт бронирование на указанный период для текущего пользователя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservation"
                ],
                "summary": "Create reservation",
                "parameters": [
                    {
                        "description": "Create reservation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.createReservationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успех",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-string"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "403": {
                        "description": "Нет доступа",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/reservation/approve": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Одобряет бронирование по reservation_id. Доступно только администратору.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservation"
                ],
                "summary": "Approve reservation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "reservation_id",
                        "name": "reservation_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Одобрено"
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Неавторизован",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "403": {
                        "description": "Только админ может одобрять",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/reservation/free-slots": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список свободных временных интервалов в заданном диапазоне.\nСвободный слот — это интервал времени, не пересекающийся ни с одной резервацией.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reservation"
                ],
                "summary": "Get free time slots",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2026-01-07T00:00:00Z",
                        "description": "Start datetime (RFC3339)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "2026-01-07T23:59:00Z",
                        "description": "End datetime (RFC3339)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of free time intervals",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-array_model_TimeRange"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        },
        "/user": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет пользователя по username. Доступно только ролям ADMIN и GOD. Нельзя удалить самого себя.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Delete user (admin/god only)",
                "parameters": [
                    {
                        "description": "Delete user request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.deleteUserRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Пользователь удалён"
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "401": {
                        "description": "Не авторизован / некорректный токен",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "403": {
                        "description": "Недостаточно прав / попытка удалить себя",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/http.DefaultResponse-error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.DefaultResponse-array_model_ChannelMessage": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ChannelMessage"
                    }
                },
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http.DefaultResponse-array_model_CinemaReservation": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.CinemaReservation"
                    }
                },
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http.DefaultResponse-array_model_Order": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Order"
                    }
                },
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http.DefaultResponse-array_model_TimeRange": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.TimeRange"
                    }
                },
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http.DefaultResponse-error": {
            "type": "object",
            "properties": {
                "data": {},
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http.DefaultResponse-http_loginResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/http.loginResponse"
                },
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http.DefaultResponse-model_Apartment": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.Apartment"
                },
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http.DefaultResponse-string": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "error_message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "http.bindApartmentRequest": {
            "type": "object",
            "required": [
                "apartment_id"
            ],
            "properties": {
                "apartment_id": {
                    "type": "string"
                }
            }
        },
        "http.confirmRequest": {
            "type": "object",
            "required": [
                "otp_code",
                "username"
            ],
            "properties": {
                "otp_code": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "http.createApartmentRequest": {
            "type": "object",
            "required": [
                "door_num",
                "floor"
            ],
            "properties": {
                "door_num": {
                    "type": "integer"
                },
                "floor": {
                    "type": "integer"
                }
            }
        },
        "http.createFeedbackRequest": {
            "type": "object",
            "required": [
                "feedback_type",
                "message"
            ],
            "properties": {
                "feedback_type": {
                    "$ref": "#/definitions/protopb.FeedbackType"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "http.createOrderRequest": {
            "type": "object",
            "properties": {
                "order_type": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "http.createReservationRequest": {
            "type": "object",
            "required": [
                "from",
                "people_num",
                "to"
            ],
            "properties": {
                "from": {
                    "type": "string"
                },
                "people_num": {
                    "type": "integer"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "http.deleteUserRequest": {
            "type": "object",
            "required": [
                "username"
            ],
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        },
        "http.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "http.loginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/model.User"
                }
            }
        },
        "http.registerRequest": {
            "type": "object",
            "required": [
                "first_name",
                "last_name",
                "password",
                "username"
            ],
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8
                },
                "username": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 3
                }
            }
        },
        "http.sendChannelMessage": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Apartment": {
            "type": "object",
            "properties": {
                "door_number": {
                    "type": "integer"
                },
                "floor": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                }
            }
        },
        "model.ChannelMessage": {
            "type": "object",
            "properties": {
                "author_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.CinemaReservation": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_approved": {
                    "type": "boolean"
                },
                "people_num": {
                    "type": "integer"
                },
                "phone_num": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.Order": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "order_type": {
                    "$ref": "#/definitions/protopb.OrderType"
                },
                "text": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "model.TimeRange": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "apartment_id": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_approved": {
                    "type": "boolean",
                    "default": false
                },
                "last_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role_id": {
                    "$ref": "#/definitions/protopb.Role"
                },
                "username": {
                    "type": "string"
                },
                "username_type": {
                    "type": "integer",
                    "default": 1
                }
            }
        },
        "protopb.FeedbackType": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2,
                3
            ],
            "x-enum-varnames": [
                "FeedbackType_FEEDBACK_UNSPECIFIED",
                "FeedbackType_PRETENSION",
                "FeedbackType_WISH",
                "FeedbackType_GRATITUDE"
            ]
        },
        "protopb.OrderType": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "x-enum-varnames": [
                "OrderType_ORDER_TYPE_UNSPECIFIED",
                "OrderType_CLEANING",
                "OrderType_INTERNET",
                "OrderType_GARBAGE_REMOVAL",
                "OrderType_PLUMBER",
                "OrderType_ELECTRICITY",
                "OrderType_OTHER"
            ]
        },
        "protopb.Role": {
            "type": "integer",
            "format": "int32",
            "enum": [
                0,
                1,
                2,
                3,
                4
            ],
            "x-enum-varnames": [
                "Role_STATUS_UNSPECIFIED",
                "Role_GUEST",
                "Role_INHABITANT",
                "Role_ADMIN",
                "Role_GOD"
            ]
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "assyl-c9b2197f0ace.herokuapp.com",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Assyl Backend API",
	Description:      "API для работы с приложением для ЖК.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
